#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/erinkelsey/Documents/01_Tools/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/erinkelsey/Dropbox/Documents/03_Portfolio/flutter/restaurant_finder_app"
export "FLUTTER_TARGET=/Users/erinkelsey/Dropbox/Documents/03_Portfolio/flutter/restaurant_finder_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/erinkelsey/Documents/01_Tools/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=ZOMATO_API_KEY%3Df5447a3d81bc6813462aaf718e00dede"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
